# https://travis-ci.org/bittner/django-organice
language: python
python:
  - "2.6"
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - python setup.py install
  - pip install flake8
before_script:
  - flake8
script:
  - make tests
notifications:
  slack:
    rooms:
      - organice:uPGToVwXE2IYAwn4hFFudPJ5#notifications
