# https://travis-ci.org/bittner/django-organice
language: python
python:
  - "2.6"
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - python setup.py install
  - pip install flake8
  - pip install coveralls
before_script:
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults
  - flake8
script:
  - python setup.py test
  - coverage run setup.py test
after_success:
  - coverage report
  - coverage xml
  - coveralls
  - mv coverage.xml shippable/codecoverage/
  - mv unittests.xml shippable/testresults/
notifications:
  slack:
    rooms:
      - organice:uPGToVwXE2IYAwn4hFFudPJ5#notifications
